version: '2.3'

services:
    flask_api_server1:
        container_name: flask-api-container
        image: flask-api-image
        build:
            context: "api/"
            dockerfile: Dockerfile
        volumes:
            - ${PWD}/api:/api
        ports:
            - "5000:5000"
        tty: true
        environment:
            TZ: "Asia/Tokyo"
            LC_ALL: C.UTF-8
            LANG: C.UTF-8
        command: bash -c "python3 app.py --host 0.0.0.0 --port 5000 --debug"

    flask_api_server2:
        container_name: flask-api-container2
        image: flask-api-image
        build:
            context: "api/"
            dockerfile: Dockerfile
        volumes:
            - ${PWD}/api:/api
        ports:
            - "5001:5001"
        tty: true
        environment:
            TZ: "Asia/Tokyo"
            LC_ALL: C.UTF-8
            LANG: C.UTF-8
        command: bash -c "python3 app.py --host 0.0.0.0 --port 5001 --debug"

    nginx_proxy_server:
        container_name: nginx-proxy-container
        image: nginx-proxy-image
        build:
            context: "proxy/"
            dockerfile: Dockerfile
        volumes:
            - ${PWD}/proxy:/proxy
        ports:
            - "8080:8080"
#        depends_on:
#            - flask_api_server1
#            - flask_api_server2
        links:
            - flask_api_server1
            - flask_api_server2
        tty: true
        environment:
            TZ: "Asia/Tokyo"
            LC_ALL: C.UTF-8
            LANG: C.UTF-8
        command: bash -c "sudo nginx -c /proxy/nginx/proxy.conf"
