version: '2.3'

services:
  mysql_server:
    container_name: mysql-container
    image: mysql:5.7
    #image: mysql:latest
    ports:
      - "3306:3306"
    tty: true
    volumes:
      - ${PWD}/mysql/my.cnf:/etc/my.cnf                         # 作成した MySQL の設定ファイル `my.cnf` を `mysql:latest` の設定ファイル `/etc/my.cnf` にマウント
      - ${PWD}/mysql/db/data:/var/lib/mysql                     # 
      - ${PWD}/mysql/db/initdb.d:/docker-entrypoint-initdb.d    # 
    restart: always                                             # 終了ステータスが異常の場合も常に再起動
    stdin_open: true                                            # コンテナの標準入力をオープンしたままにする。`docker run` での `-i` オプションに対応
    environment:                                                # MySQL の docker image `mysql` で使用される環境変数を追加
      TZ: "Asia/Tokyo"
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
      MYSQL_ROOT_PASSWORD: password                             # [必須] root ユーザーに対しての MySQL ログインパスワード
      MYSQL_USER: user                                          # [オプション] MySQL サーバー起動時に作成するデータベース名
      MYSQL_PASSWORD: password                                  # [オプション] 新規ユーザーに対しての MySQL ログインパスワード            
      MYSQL_DATABASE: "test_db"                                 # [オプション] MySQL サーバー起動時に作成するデータベース名
